# Generated by Django 3.2.14 on 2022-07-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissiongroup',
            options={'verbose_name': '权限组表', 'verbose_name_plural': '权限组表'},
        ),
        migrations.AlterField(
            model_name='permissions',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.permissiongroup', verbose_name='所属权限组'),
        ),
    ]
