# Generated by Django 3.2.14 on 2022-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20220711_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(related_name='roleToperm', to='rbac.Permissions', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ManyToManyField(related_name='userTorole', to='rbac.Role', verbose_name='角色'),
        ),
    ]
